# ====================================================================
# DO NOT EDIT THIS FILE
# These IAM roles are provided by the Titan FinTech Security Team.
# You will reference them in your main.tf file.
# ====================================================================

# Provided Role 1: For VPC Flow Logs
resource "aws_iam_role" "flow_log_role" {
  name = "Titan-FlowLog-Role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole", Effect = "Allow", Principal = { Service = "vpc-flow-logs.amazonaws.com" } }]
  })
}

resource "aws_iam_role_policy" "flow_log_policy" {
  name = "Titan-FlowLog-Policy"
  role = aws_iam_role.flow_log_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents", "logs:DescribeLogGroups", "logs:DescribeLogStreams"]
      Effect = "Allow", Resource = "*"
    }]
  })
}

# Provided Role 2: For EC2 SSM (Zero Trust) Access
resource "aws_iam_role" "ssm_role" {
  name = "Titan-SSM-Role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole", Effect = "Allow", Principal = { Service = "ec2.amazonaws.com" } }]
  })
}

resource "aws_iam_role_policy_attachment" "ssm_attach" {
  role       = aws_iam_role.ssm_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "ssm_profile" {
  name = "Titan-SSM-Profile"
  role = aws_iam_role.ssm_role.name
}

